/** USER ACTION TYPES **/

export const ON_CHANGE_USERNAME = 'ON_CHANGE_USERNAME';
export const ADD_USER = 'ADD_USER';
export const LIST_USERS = 'LIST_USERS';
export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

/** AUTH ACTION TYPES **/
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';